# config.py 파일 생성
WEATHER_API_KEY = "7PjattrxPKa0He1GbJAlAAFpR%2FtxSIyaIRwuCwEgQZCxRyh42Y3LYWWn0vrh7rovkK753c8cOqnqOeGQly%2FSqQ%3D%3D"
NAVER_CLIENT_ID = ""rXrsRKFlflMjL3Vm1VP4
NAVER_CLIENT_SECRET = "rdKxzozaql"
